# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Lire' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lire
    pod 'Alamofire'
    pod 'RealmSwift'
    pod 'SwipeCellKit'
    pod 'AlamofireImage', '~> 3.5'

  target 'LireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LireUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
